# Generated by Django 5.2.1 on 2025-05-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='エリア名')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='月')),
                ('number', models.IntegerField(unique=True, verbose_name='月番号')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='国名')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area', verbose_name='エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='観光地名')),
                ('information', models.TextField(verbose_name='詳細情報')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='myapp/picture/', verbose_name='画像')),
                ('best_season', models.ManyToManyField(blank=True, to='myapp.month', verbose_name='ベストシーズン')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country', verbose_name='国')),
            ],
            options={
                'verbose_name': '観光スポット',
                'verbose_name_plural': '観光スポット',
                'unique_together': {('country', 'name')},
            },
        ),
    ]
