# Generated by Django 5.2.1 on 2025-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/picture/', verbose_name='イメージ'),
        ),
    ]
