# Generated by Django 5.2.1 on 2025-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_spot_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='タグ名')),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='tag',
            field=models.ManyToManyField(blank=True, to='myapp.tags', verbose_name='タグ'),
        ),
    ]
